@startuml SystemContext
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Container.puml


title 商品系统视图-SYSTEM CONTEXT
LAYOUT_WITH_LEGEND()

Person(主站商家, "主站商家", "")
Person(有赞云商家, "有赞云商家", "")
Person(销售, "销售", "")
Person(财务, "财务", "")

System(商业化前台系统, "商业化前台系统", "[YOP]", "允许商家、销售或财务查看商品相关的配置数据")
System(商品系统, "商品系统", "允许商家、销售或财务查看商品相关的配置数据")
System_Ext(CRM系统, "CRM系统", "商家订购的业绩计算")
System_Ext(财务系统, "财务系统", "商家订购的返佣计算")
ContainerDb(系统基础设施, "系统基础设施", "MySQL/KVDS","存储所有的商品数据，包括软件、插件及套餐等。")

Rel(主站商家, 商品系统, "Uses")
Rel(有赞云商家, 商品系统, "Uses")
Rel(销售, 商品系统, "Uses")
Rel(财务, 商品系统, "Uses")
Rel_Back(销售, CRM系统, "业绩数据")
Rel_Back(财务, 财务系统, "返佣信息")

Rel_L(商品系统, CRM系统, "订单消息", "NSQ")
Rel_R(商品系统, 财务系统, "订单消息", "NSQ")
Rel(商品系统, 系统基础设施, "Uses")

@enduml